import type {
  Case,
  Entity,
  Evidence,
  Connection,
  Investigator,
} from "./types";

// ─── Demo Case ─────────────────────────────────────────────────────────────

export const demoCase: Case = {
  id: "demo-case",
  title: "The Meridian Protocol",
  subtitle: "A web of corporate espionage runs deeper than anyone imagined",
  description:
    "When a senior data architect at Meridian Systems is found dead in his office, what appears to be a tragic suicide quickly unravels into a labyrinth of corporate espionage, insider trading, and a shadowy network that reaches into the highest echelons of power. Five suspects. Ten pieces of evidence. One truth hidden beneath layers of deception.",
  status: "active",
  difficulty: 4,
  dateOpened: "2026-03-15",
  location: "Seattle, WA",
  entityCount: 5,
  evidenceCount: 10,
  connectionCount: 8,
};

// ─── Entities ──────────────────────────────────────────────────────────────

export const entities: Entity[] = [
  {
    id: "ent-001",
    caseId: "demo-case",
    name: "Dr. Marcus Webb",
    type: "victim",
    description:
      "Senior data architect at Meridian Systems. Found dead in his locked office on March 14th. Known for his meticulous work habits and a growing unease in the weeks before his death.",
    age: 47,
    occupation: "Senior Data Architect",
    lastKnownLocation: "Meridian Systems HQ, Floor 34",
    status: "Deceased",
  },
  {
    id: "ent-002",
    caseId: "demo-case",
    name: "Elena Vasquez",
    type: "suspect",
    description:
      'Chief Technology Officer at Meridian Systems. Promoted over Webb six months ago despite his seniority. Multiple witnesses report heated arguments between them. Her access keycard shows she was in the building until 11:47 PM on the night in question.',
    age: 39,
    occupation: "CTO, Meridian Systems",
    lastKnownLocation: "Meridian Systems HQ",
    status: "Under investigation",
  },
  {
    id: "ent-003",
    caseId: "demo-case",
    name: "James Harlow",
    type: "person_of_interest",
    description:
      "Private security consultant with ties to multiple corporate intelligence firms. Surveillance footage places him at a restaurant with Webb three days before the death. No prior known connection between the two.",
    age: 52,
    occupation: "Private Security Consultant",
    lastKnownLocation: "Unknown",
    status: "Whereabouts unknown",
  },
  {
    id: "ent-004",
    caseId: "demo-case",
    name: "Sarah Chen",
    type: "witness",
    description:
      "Junior developer at Meridian Systems and the last person to see Webb alive. Claims she left his office at 8 PM after discussing a routine code review. Her testimony contains inconsistencies about the timeline.",
    age: 28,
    occupation: "Software Developer",
    lastKnownLocation: "Meridian Systems HQ",
    status: "Cooperating witness",
  },
  {
    id: "ent-005",
    caseId: "demo-case",
    name: "Nexus Capital Group",
    type: "organization",
    description:
      'A venture capital firm with significant investment in Meridian Systems. Internal documents suggest they were pressuring the board for access to proprietary datasets codenamed "Protocol-7". Webb was the primary gatekeeper of these datasets.',
    occupation: "Venture Capital Firm",
    lastKnownLocation: "Financial District, Seattle",
    status: "Under regulatory review",
  },
];

// ─── Evidence ──────────────────────────────────────────────────────────────

export const evidence: Evidence[] = [
  {
    id: "ev-001",
    caseId: "demo-case",
    title: "Webb's Encrypted Laptop",
    type: "digital",
    description:
      "Personal laptop found in Webb's home office. Contains multiple layers of encryption. Forensic analysis reveals recently deleted files related to Project Protocol-7.",
    dateCollected: "2026-03-15",
    location: "Webb Residence",
    linkedEntityIds: ["ent-001"],
    credibility: 5,
    classified: false,
  },
  {
    id: "ev-002",
    caseId: "demo-case",
    title: "Security Footage — Lobby",
    type: "photo",
    description:
      "Lobby security camera footage showing Elena Vasquez entering the building at 10:15 PM and leaving at 11:47 PM. Notably, she used the freight elevator rather than the main elevator bank.",
    dateCollected: "2026-03-15",
    location: "Meridian Systems HQ",
    linkedEntityIds: ["ent-002"],
    credibility: 5,
    classified: false,
  },
  {
    id: "ev-003",
    caseId: "demo-case",
    title: "Burner Phone Records",
    type: "communication",
    description:
      "Records from a prepaid phone found in Webb's desk drawer. Shows 17 calls to an unregistered number in the 72 hours before his death. Cell tower triangulation places the other phone near James Harlow's known residence.",
    dateCollected: "2026-03-16",
    location: "Meridian Systems HQ, Webb's Office",
    linkedEntityIds: ["ent-001", "ent-003"],
    credibility: 4,
    classified: false,
  },
  {
    id: "ev-004",
    caseId: "demo-case",
    title: "Autopsy Report",
    type: "forensic",
    description:
      "Official cause of death: asphyxiation. However, toxicology reports reveal traces of a rare sedative compound not consistent with Webb's known medical prescriptions. Bruising patterns on the wrists suggest restraint.",
    dateCollected: "2026-03-16",
    location: "King County Medical Examiner",
    linkedEntityIds: ["ent-001"],
    credibility: 5,
    classified: true,
  },
  {
    id: "ev-005",
    caseId: "demo-case",
    title: "Nexus Capital Board Minutes",
    type: "document",
    description:
      'Leaked board meeting minutes from Nexus Capital Group dated February 28th. Discussion item: "Acquisition of Protocol-7 assets — timeline acceleration required." Handwritten margin note reads: "Webb is the obstacle."',
    dateCollected: "2026-03-18",
    location: "Anonymous source",
    linkedEntityIds: ["ent-005", "ent-001"],
    credibility: 3,
    classified: false,
  },
  {
    id: "ev-006",
    caseId: "demo-case",
    title: "Chen's Revised Timeline",
    type: "testimony",
    description:
      "During a second interview, Sarah Chen revised her departure time from 8 PM to 9:30 PM. She also mentioned overhearing a phone call where Webb sounded 'desperate' and mentioned 'they won't stop until they get it.'",
    dateCollected: "2026-03-19",
    location: "Police Station",
    linkedEntityIds: ["ent-004", "ent-001"],
    credibility: 3,
    classified: false,
  },
  {
    id: "ev-007",
    caseId: "demo-case",
    title: "Wire Transfer Records",
    type: "financial",
    description:
      "Bank records showing three wire transfers totaling $2.3M from a Nexus Capital subsidiary to a shell company in the Cayman Islands. The shell company's registered agent matches a known alias used by James Harlow.",
    dateCollected: "2026-03-20",
    location: "First National Bank",
    linkedEntityIds: ["ent-005", "ent-003"],
    credibility: 4,
    classified: true,
  },
  {
    id: "ev-008",
    caseId: "demo-case",
    title: "Vasquez's Personal Email",
    type: "communication",
    description:
      'Emails recovered from Elena Vasquez\'s personal account showing correspondence with an unknown party. Message from March 12: "The architect knows too much. We need to move to Phase 3 before the board meeting."',
    dateCollected: "2026-03-21",
    location: "Digital forensics lab",
    linkedEntityIds: ["ent-002"],
    credibility: 4,
    classified: false,
  },
  {
    id: "ev-009",
    caseId: "demo-case",
    title: "Office Lock Analysis",
    type: "physical",
    description:
      "Electronic lock log for Webb's office shows the door was locked from the outside at 10:52 PM using a master keycard. Only three master keycards exist: building management, CEO, and CTO (Vasquez).",
    dateCollected: "2026-03-15",
    location: "Meridian Systems HQ, Floor 34",
    linkedEntityIds: ["ent-001", "ent-002"],
    credibility: 5,
    classified: false,
  },
  {
    id: "ev-010",
    caseId: "demo-case",
    title: "Restaurant Surveillance",
    type: "photo",
    description:
      "Surveillance footage from Il Cortile restaurant showing Webb and Harlow at a corner booth on March 11. Webb appears to hand Harlow a USB drive. Harlow places an envelope on the table.",
    dateCollected: "2026-03-22",
    location: "Il Cortile Restaurant",
    linkedEntityIds: ["ent-001", "ent-003"],
    credibility: 4,
    classified: false,
  },
];

// ─── Connections ───────────────────────────────────────────────────────────

export const connections: Connection[] = [
  {
    id: "conn-001",
    caseId: "demo-case",
    sourceEntityId: "ent-002",
    targetEntityId: "ent-001",
    type: "professional",
    label: "Superior / Subordinate conflict",
    strength: 4,
    verified: true,
  },
  {
    id: "conn-002",
    caseId: "demo-case",
    sourceEntityId: "ent-003",
    targetEntityId: "ent-001",
    type: "suspicious",
    label: "Secret meeting at Il Cortile",
    strength: 4,
    verified: true,
  },
  {
    id: "conn-003",
    caseId: "demo-case",
    sourceEntityId: "ent-005",
    targetEntityId: "ent-001",
    type: "motive",
    label: 'Protocol-7 data access — "Webb is the obstacle"',
    strength: 5,
    verified: false,
  },
  {
    id: "conn-004",
    caseId: "demo-case",
    sourceEntityId: "ent-005",
    targetEntityId: "ent-003",
    type: "financial",
    label: "$2.3M via shell company",
    strength: 4,
    verified: true,
  },
  {
    id: "conn-005",
    caseId: "demo-case",
    sourceEntityId: "ent-004",
    targetEntityId: "ent-001",
    type: "professional",
    label: "Last person to see victim alive",
    strength: 3,
    verified: true,
  },
  {
    id: "conn-006",
    caseId: "demo-case",
    sourceEntityId: "ent-002",
    targetEntityId: "ent-005",
    type: "communication",
    label: '"Move to Phase 3" email exchange',
    strength: 4,
    verified: false,
  },
  {
    id: "conn-007",
    caseId: "demo-case",
    sourceEntityId: "ent-003",
    targetEntityId: "ent-001",
    type: "communication",
    label: "17 burner phone calls in 72 hours",
    strength: 3,
    verified: true,
  },
  {
    id: "conn-008",
    caseId: "demo-case",
    sourceEntityId: "ent-002",
    targetEntityId: "ent-001",
    type: "physical",
    label: "Master keycard used to lock office at 10:52 PM",
    strength: 5,
    verified: true,
  },
];

// ─── Leaderboard ───────────────────────────────────────────────────────────

export const leaderboard: Investigator[] = [
  {
    id: "inv-001",
    name: "Alexandra Frost",
    rank: "chief_inspector",
    casesSolved: 142,
    accuracy: 97,
    streak: 23,
    score: 48750,
    joinedDate: "2024-01-15",
  },
  {
    id: "inv-002",
    name: "Marcus Liu",
    rank: "inspector",
    casesSolved: 98,
    accuracy: 94,
    streak: 15,
    score: 35200,
    joinedDate: "2024-03-22",
  },
  {
    id: "inv-003",
    name: "Diana Okafor",
    rank: "inspector",
    casesSolved: 87,
    accuracy: 91,
    streak: 8,
    score: 31450,
    joinedDate: "2024-02-10",
  },
  {
    id: "inv-004",
    name: "James Thornton",
    rank: "senior_detective",
    casesSolved: 76,
    accuracy: 89,
    streak: 12,
    score: 27800,
    joinedDate: "2024-05-01",
  },
  {
    id: "inv-005",
    name: "Yuki Tanaka",
    rank: "senior_detective",
    casesSolved: 64,
    accuracy: 93,
    streak: 19,
    score: 24100,
    joinedDate: "2024-04-18",
  },
  {
    id: "inv-006",
    name: "Rafael Moreno",
    rank: "detective",
    casesSolved: 51,
    accuracy: 86,
    streak: 5,
    score: 18900,
    joinedDate: "2024-06-12",
  },
  {
    id: "inv-007",
    name: "Ingrid Bergström",
    rank: "detective",
    casesSolved: 43,
    accuracy: 88,
    streak: 7,
    score: 15600,
    joinedDate: "2024-07-30",
  },
  {
    id: "inv-008",
    name: "Kwame Asante",
    rank: "rookie",
    casesSolved: 12,
    accuracy: 92,
    streak: 4,
    score: 8400,
    joinedDate: "2025-01-05",
  },
];
